import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Layout } from "@/components/layout";

export default function Home() {
  const router = useRouter();
  const user = true;
  useEffect(() => {
    if (user) {
      router.push("/auth/sign-in");
    }
  }, [user]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div>Home</div>
      </Layout>
    </>
  );
}
