import Head from "next/head";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  const user = false;
  if (!user) {
    router.push("/auth/sign-in");
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="flex w-full flex-col">
          <p>
            Hello&nbsp;
            <code>pages/index.tsx</code>
          </p>
        </div>
      </main>
    </>
  );
}
