import {
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowersProfilePublic,
  getFollowingsProfile,
  getPublicPlaylist,
  getPublicProfile,
  getPublicUploades,
  getRecommendedByProfile,
  getUploades,
  updateFollower,
} from "#/controllers/profile";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";

const router = Router();

router.post("/update-follower/:profileId", mustAuth, updateFollower);
router.get("/uploads", mustAuth, getUploades);
router.get("/uploads/:profileId", getPublicUploades);
router.get("/info/:profileId", getPublicProfile);
router.get("/playlist/:profileId", getPublicPlaylist);
router.get("/recommended", isAuth, getRecommendedByProfile);
router.get("/auto-generated-playlist", mustAuth,getAutoGeneratedPlaylist );
router.get("/followers", mustAuth,getFollowersProfile );
router.get("/followers/:profileId", mustAuth,getFollowersProfilePublic );
router.get("/followings", mustAuth,getFollowingsProfile );


export default router;
